### ISSUE TITLE
Cache key error when DN is unicode

### ISSUE THREAD

**Issue by nijel** [django-auth-ldap/django-auth-ldap#20] opened 2018-04-13 18:10 UTC
When AUTH_LDAP_CACHE_GROUPS is True and user DN contains unicode chars, following error happens when cache backend does not support unicode keys:

```
  File "/app/weblate/.local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 277, in has_perm
    return _user_has_perm(self, perm, obj)
  File "/app/weblate/.local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 190, in _user_has_perm
    if backend.has_perm(user, perm, obj):
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 183, in has_perm
    return perm in self.get_all_permissions(user, obj)
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 193, in get_all_permissions
    return self.get_group_permissions(user, obj)
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 200, in get_group_permissions
    return user.ldap_user.get_group_permissions()
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 367, in get_group_permissions
    self._load_group_permissions()
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 690, in _load_group_permissions
    group_names = self._get_groups().get_group_names()
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 789, in get_group_names
    self._load_cached_attr("_group_names")
  File "/usr/lib/python2.7/dist-packages/django_auth_ldap/backend.py", line 847, in _load_cached_attr
    value = cache.get(key)
  File "/usr/lib/python2.7/dist-packages/django_redis/cache.py", line 34, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django_redis/cache.py", line 83, in get
    client=client)
  File "/usr/lib/python2.7/dist-packages/django_redis/client/default.py", line 204, in get
    key = self.make_key(key, version=version)
  File "/usr/lib/python2.7/dist-packages/django_redis/client/default.py", line 523, in make_key
    return CacheKey(self._backend.key_func(key, prefix, version))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 63: ordinal not in range(128)
```

**Comment by nijel** [comment] 2018-04-13 18:17
I've tried to fix this, but I could not test the fix: https://github.com/django-auth-ldap/django-auth-ldap/pull/21

**Comment by jdufresne** [comment] 2018-06-01 02:33
I've tried, but am unable to reproduce this error.

What version of Django are you using?  What version of django-redis? Have you defined a custom [`KEY_FUNCTION`](https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-CACHES-KEY_FUNCTION)?

Do you have any additional information as to how to reproduce this error?

**Comment by nijel** [comment] 2018-06-01 08:12
This is with 1.11.11, no custom KEY_FUNCTION is used, redis cache backend is used (this certainly won't cause problems with default local memory cache).

**Comment by jdufresne** [comment] 2018-06-01 13:08
What version of django-redis?

**Comment by jdufresne** [comment] 2018-06-01 14:03
Here is my attempt to write a failing test. However, it does not fail on Python 2.7 with Django 1.11. Please try to run it to see if it fails for you and report the results. If not, please try to adjust the test so it better represents your use case such that it will fail.

https://github.com/jdufresne/django-auth-ldap/commit/0889fc4f962f0319bd36dbd6bb264a0d629730b6

Without a failing test or reliable steps to reproduce, I'm hesitant to make a code change.

What OS are you running?

**Comment by nijel** [comment] 2018-06-02 06:33
It's on Debian stretch, django-redis version 4.7.0.

**Comment by jdufresne** [comment] 2018-06-02 14:10
I think you're experiencing a bug in django-redis. My test above fails with django-redis 4.7.0, but passes OK on 4.9.0. Can you upgrade django-redis to see if the problem continues to exist?

**Comment by jdufresne** [comment] 2018-07-05 13:43
If you get back to this and discover a reproducible bug in django-auth-ldap, please reopen or leave a comment. Until this, it seems the error is elsewhere, so I'm closing.

**Closed by jdufresne** 2018-07-05 13:43 UTC
