### ISSUE TITLE
AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.

### ISSUE THREAD

**Issue by fleonasb** [django-auth-ldap/django-auth-ldap#88] opened 2018-08-31 11:11 UTC
I'm trying to setup multiple LDAP backends. I have already created a multiple_ldap.py file:
```
from django_auth_ldap.backend import LDAPBackend
class LDAPBackend1(LDAPBackend):
    settings_prefix = "AUTH_LDAP_1"
class LDAPBackend2(LDAPBackend):
    settings_prefix = "AUTH_LDAP_2"
```
added two LDAP backends:
```
AUTHENTICATION_BACKENDS = [
    'myapp.multiple_ldap.LDAPBackend1',
    'myapp.multiple_ldap.LDAPBackend2',
]
```
and started renaming the AUTH_LDAP_ settings to match my setup.

When I try to log in, I get this exception:

> ImproperlyConfigured at /myapp/django-admin/login/
> AUTH_LDAP_USER_SEARCH must be an LDAPSearch instance.

**Comment by jdufresne** [comment] 2018-08-31 14:12
Sounds like either `AUTH_LDAP_1_USER_SEARCH` or `AUTH_LDAP_2_USER_SEARCH` is not set correctly. Can you provide all LDAP settings to verify?

**Comment by pgastinger** [comment] 2018-09-16 13:05
If this is still an open issue, I ran into the same problem. 

I originally had only one LDAP-setting in my AUTHENTICATION_BACKENDS and forget to remove that setting for the new, multiple LDAPBackend-entries. So basically the original setting was looking for entries with AUTH_LDAP_-prefix in my settings, which was not available anymore. 

After changing that, it worked.

**Comment by jdufresne** [comment] 2018-09-16 16:00
It sounds like this may be a misconfiguration and not a bug in django-auth-ldap. Do you agree? 

If you think anything could be improved to make this easier, either in the docs or code, please let me know.

**Comment by jdufresne** [comment] 2018-10-01 12:34
Closing as it seems this is not a bug.

**Closed by jdufresne** 2018-10-01 12:34 UTC
Labels: question
